project_name: meridian
before:
  hooks:
  - go mod download
builds:
- id: "default"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .CommitDate }}
brews:
- tap:
    owner: mrflynn
    name: homebrew-cider
  commit_author:
    name: goreleaser
    email: actions@users.noreply.github.com
  caveats: "Run meridian info for a list of available data."
  homepage: "https://github.com/mrflynn/meridian"
  description: "A tool for getting information about your current location."
archives:
- id: "default"
  builds:
  - default
checksum:
  name_template: "SHASUMS.txt"
snapshot:
  name_template: "{{ .Tag }}-RC-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^conf(ig)?:"